[package]
name = "lakefs-test-utils"
version.workspace = true
edition.workspace = true

[dependencies]
lakefs-api = { path = "../lakefs-api" }
chrono = "0.4"
wiremock = "0.5"
serde_json = "1.0"
tempfile = "3.8"
